(function(){
  'use strict';
  const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
  const wait=ms=>new Promise(r=>setTimeout(r,ms));
  const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  const duration=ms=>reduced?Math.min(ms,120):ms;
  const save=(key,value='true')=>{try{localStorage.setItem('sofia-'+key,value)}catch{}};
  let soundEnabled=false;
  let audioContext=null;
  const soundButton=$('[data-sound-toggle]');
  function setupAtenaEffect(){if(audioContext)return;const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return;audioContext=new AudioContext();$$('audio[data-atena]').forEach(a=>{const source=audioContext.createMediaElementSource(a),dry=audioContext.createGain(),filter=audioContext.createBiquadFilter(),delay=audioContext.createDelay(.12),wet=audioContext.createGain();dry.gain.value=.82;filter.type='bandpass';filter.frequency.value=1450;filter.Q.value=.7;delay.delayTime.value=.038;wet.gain.value=.3;source.connect(dry).connect(audioContext.destination);source.connect(filter).connect(delay).connect(wet).connect(audioContext.destination);});}
  function unlockSound(){if(soundEnabled)return;setupAtenaEffect();audioContext?.resume();soundEnabled=true;const audios=$$('audio[data-atena]');const starts=audios.map(a=>{a.muted=true;const started=a.play();return Promise.resolve(started).then(()=>{a.pause();a.currentTime=0;a.muted=false;}).catch(()=>{a.muted=false;});});Promise.all(starts).then(()=>{soundButton.textContent='som ativado';soundButton.setAttribute('aria-pressed','true');});}
  soundButton?.addEventListener('click',unlockSound);
  const playVoice=n=>new Promise(resolve=>{if(!soundEnabled){resolve();return;}const a=$(`[data-atena="${n}"]`);if(!a){resolve();return;}$$('audio[data-atena]').forEach(x=>{if(x!==a&&!x.paused){x.pause();x.currentTime=0;}});a.currentTime=0;let done=false,timer;const finish=()=>{if(done)return;done=true;clearTimeout(timer);a.removeEventListener('ended',finish);a.removeEventListener('error',finish);resolve();};a.addEventListener('ended',finish,{once:true});a.addEventListener('error',finish,{once:true});const limit=Number.isFinite(a.duration)?Math.min((a.duration+1.5)*1000,20000):15000;timer=setTimeout(finish,limit);a.play().catch(()=>{soundButton.textContent='toque para ativar o som';soundButton.setAttribute('aria-pressed','false');soundEnabled=false;finish();});});
  const reveal=el=>{el.hidden=false;requestAnimationFrame(()=>el.scrollIntoView({behavior:reduced?'auto':'smooth',block:'start'}));};

  const phone=$('[data-phone]'), flashlight=$('[data-flashlight]');
  const finalHum=$('[data-final-hum]'),humButton=$('[data-hum-toggle]');
  const updateHumButton=playing=>{if(!humButton)return;humButton.setAttribute('aria-pressed',String(playing));humButton.textContent=playing?'silenciar o sussurro':'ouvir o sussurro';};
  let humFade=null;
  const pararHum=()=>{clearInterval(humFade);humFade=null;if(!finalHum)return;finalHum.pause();finalHum.currentTime=0;finalHum.volume=.4;updateHumButton(false);};
  const startFinalHum=()=>{if(!finalHum)return;clearInterval(humFade);finalHum.volume=.4;finalHum.currentTime=0;finalHum.play().then(()=>{updateHumButton(true);humFade=setInterval(()=>{const resta=finalHum.duration-finalHum.currentTime;if(!Number.isFinite(resta))return;if(resta<=8)finalHum.volume=Math.max(0,.4*(resta/8));},120);}).catch(()=>updateHumButton(false));};
  finalHum?.addEventListener('ended',pararHum);
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&finalHum&&!finalHum.paused)pararHum();});
  humButton?.addEventListener('click',()=>{if(finalHum.paused)startFinalHum();else pararHum();});
  flashlight?.addEventListener('click',async()=>{if(phone.classList.contains('is-dead'))return;unlockSound();flashlight.disabled=true;$('[data-phone-status]').textContent='A lanterna não respondeu.';await wait(duration(650));phone.classList.add('is-glitching');$('[data-battery]').textContent='1%';await wait(duration(520));phone.classList.remove('is-glitching');phone.classList.add('is-dead');$('[data-phone-status]').textContent='A tela apagou.';await wait(duration(700));startCeremony();});

  async function startCeremony(){const scene=$('[data-ceremony]');reveal(scene);await wait(duration(800));for(const el of $$('.representative',scene)){scene.classList.add('has-interference');el.classList.add('is-flashing');await wait(duration(780));el.classList.remove('is-flashing');scene.classList.remove('has-interference');await wait(duration(260));}$('.ceremony-darkness',scene).style.opacity='.62';$('[data-ceremony-caption]').innerHTML='<p><strong>Sofia.</strong></p><p>Você veio procurar respostas. Comece olhando.</p>';await playVoice(1);scene.classList.add('is-transitioning');reveal($('[data-trial-one]'));await playVoice(2);}

  const objectData={
    card:{title:'Cartão de acesso',copy:'Um objeto claramente fora de época, parcialmente escondido entre os livros.',sofia:'— Isso definitivamente não pertence à estante.'},
    hourglass:{title:'Ampulheta inversa',copy:'Durante dois segundos, parece uma ampulheta comum.',sofia:'— Ah. Retiro o que disse.'},
    page:{title:'Fragmento de Tales',copy:'Um pedaço da página que apareceu no caderno durante a aula de Ciências.',sofia:'— Eu conheço isso.'}
  };
  const found=new Set();let currentObject=null;
  $$('[data-object]').forEach(btn=>btn.addEventListener('click',async()=>{currentObject=btn.dataset.object;const d=objectData[currentObject],dialog=$('[data-inspect-dialog]'),art=$('[data-inspect-art]');art.dataset.object=currentObject;art.setAttribute('aria-label',d.title);$('[data-inspect-title]').textContent=d.title;$('[data-inspect-copy]').textContent=d.copy;$('[data-inspect-sofia]').textContent=currentObject==='hourglass'?'':d.sofia;$('[data-mark-intruder]').disabled=found.has(currentObject);$('[data-mark-intruder]').textContent=found.has(currentObject)?'Intruso marcado':'Marcar como intruso';dialog.showModal();if(currentObject==='hourglass'){await wait(duration(2000));art.classList.add('is-reversing');$('[data-inspect-copy]').textContent='A areia sobe da parte inferior para a superior.';$('[data-inspect-sofia]').textContent=d.sofia;}}));
  const studyObservations={globe:'O globo está no lugar certo. Sofia reconhece até a marca de poeira na base.',astrolabe:'O astrolábio é antigo, mas pertence à sala. Nenhuma peça se move sozinha.',magnifier:'A lupa amplia riscos comuns na madeira. Nada foi escondido sob ela.',window:'A janela mostra o pátio de sempre. Por enquanto.'};
  $$('[data-distractor]').forEach(btn=>btn.addEventListener('click',()=>{const key=btn.dataset.distractor;btn.querySelector('span').textContent='observado';$('[data-study-observation]').textContent=studyObservations[key];setTimeout(()=>btn.querySelector('span').textContent='examinar',1400)}));
  const resetInspectZoom=()=>{const art=$('[data-inspect-art]'),button=$('[data-inspect-zoom]');art.classList.remove('is-zoomed');button.setAttribute('aria-pressed','false');button.textContent='ampliar objeto';};
  $('[data-inspect-zoom]')?.addEventListener('click',()=>{const art=$('[data-inspect-art]'),button=$('[data-inspect-zoom]'),zoomed=art.classList.toggle('is-zoomed');button.setAttribute('aria-pressed',String(zoomed));button.textContent=zoomed?'reduzir objeto':'ampliar objeto';});
  $('[data-inspect-art]')?.addEventListener('click',()=> $('[data-inspect-zoom]')?.click());
  $('[data-inspect-dialog]')?.addEventListener('close',resetInspectZoom);
  $('[data-close-inspect]')?.addEventListener('click',()=>{$('[data-inspect-dialog]').close();$('[data-inspect-art]').classList.remove('is-reversing');resetInspectZoom();});
  $('[data-mark-intruder]')?.addEventListener('click',async()=>{if(!currentObject||found.has(currentObject))return;found.add(currentObject);$(`[data-object="${currentObject}"]`).classList.add('is-found');$('[data-trial-one-status]').textContent=`${found.size} de 3 intrusos marcados.`;$('[data-inspect-dialog]').close();resetInspectZoom();if(found.size===3){save('teste1_concluido');await wait(duration(650));await dismantleStudy();}});
  async function dismantleStudy(){const stage=$('[data-study-stage]');stage.classList.add('is-dismantling');stage.animate([{filter:'none',opacity:1},{filter:'blur(3px) grayscale(1)',opacity:.28},{filter:'blur(12px)',opacity:0}],{duration:duration(2200),fill:'forwards'});await Promise.all([playVoice(3),wait(duration(2300))]);reveal($('[data-trial-two]'));}

  const flipped=new Set();
  $$('[data-token]').forEach(btn=>btn.addEventListener('click',()=>{btn.setAttribute('aria-pressed','true');flipped.add(btn.dataset.token);if(flipped.size===3)$('[data-letter-choice]').hidden=false;}));
  let cipherEntry='';
  const renderCipher=()=>{$$('[data-cipher-word] span').forEach((slot,i)=>slot.textContent=cipherEntry[i]||'_');$('[data-cipher-feedback]').textContent=`${cipherEntry.length} de 5 letras.`;};
  const resetCipher=()=>{cipherEntry='';renderCipher();};
  $$('[data-letter]').forEach(btn=>btn.addEventListener('click',()=>{if(cipherEntry.length>=5)return;cipherEntry+=btn.dataset.letter;renderCipher();if(cipherEntry.length<5)return;if(cipherEntry!=='PENSE'){const word=$('[data-cipher-word]');word.classList.add('is-wrong');$('[data-cipher-feedback]').textContent='A sequência não corresponde aos glifos. Tente de novo.';setTimeout(()=>{word.classList.remove('is-wrong');resetCipher();},850);return;}$('[data-cipher-word]').classList.add('is-solved');$('[data-letter-choice]').hidden=true;$('[data-cipher-reaction]').hidden=false;$('[data-cipher-continue]').hidden=false;save('teste2_concluido');}));
  $('[data-cipher-erase]')?.addEventListener('click',()=>{cipherEntry=cipherEntry.slice(0,-1);renderCipher();});
  $('[data-cipher-continue]')?.addEventListener('pointerenter',breakCipher,{once:true});
  $('[data-cipher-continue]')?.addEventListener('focus',breakCipher,{once:true});
  $('[data-cipher-continue]')?.addEventListener('click',breakCipher,{once:true});
  let cipherBreaking=false;
  async function breakCipher(){if(cipherBreaking)return;cipherBreaking=true;const section=$('[data-trial-two]'),button=$('[data-cipher-continue]');button.hidden=true;section.classList.add('is-breaking');await Promise.all([playVoice(4),wait(duration(1500))]);reveal($('[data-doubt]'));buildDoubt();}
  const doubtSymbols=['◇','◌','⧖','┆','⬡','◐'],doubtOrder=[2,0,4,1,5,3],doubtWord='DUVIDE';
  let doubtProgress=0,doubtRun=0,doubtSolved=false;
  const resetDoubt=()=>{const host=$('[data-doubt-glyphs]');doubtProgress=0;$$('.doubt-glyph',host).sort((a,b)=>Number(a.dataset.index)-Number(b.dataset.index)).forEach((b,i)=>{b.textContent=doubtSymbols[i];b.classList.remove('is-stable','is-pulsing');b.disabled=true;b.setAttribute('aria-label',`Glifo ${i+1}`);host.append(b);});};
  async function playDoubtSequence(){const run=++doubtRun,status=$('[data-doubt-progress]'),replay=$('[data-doubt-replay]');resetDoubt();const buttons=$$('.doubt-glyph',$('[data-doubt-glyphs]')).sort((a,b)=>Number(a.dataset.index)-Number(b.dataset.index));replay.hidden=true;status.textContent='Observe a sequência.';if(reduced){status.textContent='Sequência: 3, 1, 5, 2, 6, 4.';}else{for(const index of doubtOrder){if(run!==doubtRun)return;const b=buttons[index];b.classList.add('is-pulsing');await wait(520);b.classList.remove('is-pulsing');await wait(180);}}if(run!==doubtRun)return;buttons.forEach(b=>b.disabled=false);replay.hidden=false;status.textContent=reduced?'Repita a sequência indicada.':'Agora repita a sequência.';}
  function buildDoubt(){const host=$('[data-doubt-glyphs]');doubtSolved=false;host.replaceChildren(...doubtSymbols.map((symbol,i)=>{const b=document.createElement('button');b.type='button';b.className='doubt-glyph';b.dataset.index=String(i);b.textContent=symbol;b.disabled=true;b.setAttribute('aria-label',`Glifo ${i+1}`);b.addEventListener('click',async()=>{if(doubtSolved||b.disabled)return;if(i!==doubtOrder[doubtProgress]){b.classList.add('is-wrong');$('[data-doubt-progress]').textContent='Sinal incorreto. A sequência vai recomeçar.';$$('.doubt-glyph',host).forEach(g=>g.disabled=true);await wait(850);b.classList.remove('is-wrong');playDoubtSequence();return;}b.textContent=doubtWord[doubtProgress];b.classList.add('is-stable');b.disabled=true;b.setAttribute('aria-label',`Letra ${doubtWord[doubtProgress]} estabilizada`);doubtProgress++;$('[data-doubt-progress]').textContent=doubtProgress===6?'DUVIDE':`${doubtProgress} de 6 sinais corretos.`;if(doubtProgress===6){doubtSolved=true;$('[data-doubt-replay]').hidden=true;finishDoubt();}});return b;}));playDoubtSequence();}
  $('[data-doubt-replay]')?.addEventListener('click',playDoubtSequence);
  async function finishDoubt(){await wait(duration(650));$('[data-doubt-paper]').style.opacity='0';document.body.classList.add('post3-silence');await wait(duration(1000));await playVoice(5);reveal($('[data-trial-three]'));}

  const observations={box:'O símbolo da tampa tem uma pequena assimetria. Parece deliberada.',key:'A chave parece corresponder à fechadura. Isso não prova que deva ser usada.',envelope:'Para quem decidir antes de obedecer. Dentro: “Uma ordem não se torna verdadeira porque foi pronunciada por uma voz que você respeita.”'};
  $$('[data-judgment-object]').forEach(btn=>btn.addEventListener('click',()=>{$('[data-judgment-observation]').innerHTML=`<p>${observations[btn.dataset.judgmentObject]}</p>`;}));
  let decision='';
  $$('[data-decision]').forEach(btn=>btn.addEventListener('click',()=>{decision=btn.dataset.decision;$('[data-decision-dialog]').showModal();}));
  $('[data-decision-form]')?.addEventListener('submit',async e=>{e.preventDefault();const reason=new FormData(e.currentTarget).get('reason');if(!reason){$('[data-decision-error]').textContent='Escolha a razão que mais se aproxima da sua decisão.';return;}save('decisao_teste3',decision);save('justificativa_teste3',reason);$('[data-decision-dialog]').close();save('teste3_concluido');reveal($('[data-box-reveal]'));await wait(duration(3600));reveal($('[data-return-ceremony]'));});
  $('[data-destiny-look]')?.addEventListener('click',async()=>{const c=$('[data-return-ceremony]');c.classList.add('is-destiny-glitch');await wait(duration(380));c.classList.remove('is-destiny-glitch');c.classList.add('is-destiny-seen');$('[data-destiny-reaction]').hidden=false;await wait(duration(1800));reveal($('[data-epilogue]'));$('[data-final-nav]').hidden=false;});
  let attempts=0;
  $('[data-test-four]')?.addEventListener('click',e=>{attempts++;const ep=$('[data-epilogue]'),botao=e.currentTarget;$('[data-access-status]').textContent=attempts>1?'ACESSO NEGADO':'ACESSO NEGADO // INSISTA';botao.classList.toggle('is-insisting',attempts===1);if(attempts>1){ep.classList.add('is-failing');setTimeout(()=>{ep.classList.remove('is-failing');$('[data-irregularity-form]').hidden=false;$('[data-irregularity-form] input').focus();},900);}});
  $('[data-irregularity-form]')?.addEventListener('submit',async e=>{e.preventDefault();const input=e.currentTarget.querySelector('input');input.value='';await wait(duration(500));input.value='NENHUMA.';await wait(duration(800));save('post3_concluido');const signal=$('[data-last-signal]');reveal(signal);await wait(duration(1300));signal.style.opacity='0';await wait(duration(450));signal.hidden=true;const ending=$('[data-final-echo]');reveal(ending);startFinalHum();$('[data-final-nav]').hidden=false;});
})();
