(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const profiles={
  heraclito:{name:'Heráclito',theme:'fire',hp:100,speed:38,basic:'IMPULSO DO FLUXO',principle:'CHAMA DO DEVIR',special:'FLUXO ETERNO',phrase:'Tudo está em movimento.',basicDamage:8,principleDamage:12,principleRange:34,specialDamage:22,specialRange:48},
  parmenides:{name:'Parmênides',theme:'stone',hp:112,speed:29,basic:'IMPACTO IMUTÁVEL',principle:'PILARES DO SER',special:'O SER É',phrase:'O ser é uno, eterno e imutável.',basicDamage:6,principleDamage:10,principleRange:31,specialDamage:14,specialRange:30},
  anaximenes:{name:'Anaxímenes',theme:'air',hp:94,speed:43,basic:'RAJADA BREVE',principle:'SOPRO TRANSFORMADOR',special:'SOPRO PRIMORDIAL',phrase:'O ar é o princípio de tudo.',basicDamage:7,principleDamage:10,principleRange:38,specialDamage:20,specialRange:54},
  anaximandro:{name:'Anaximandro',theme:'apeiron',hp:100,speed:33,basic:'FRAGMENTO INCERTO',principle:'ORBE DO ÁPEIRON',special:'ÁPEIRON',phrase:'Tudo vem do ápeiron, o ilimitado.',basicDamage:7,principleDamage:11,principleRange:44,specialDamage:19,specialRange:58}
};
const ui={frame:$('.fight-frame'),selection:$('[data-selection]'),arena:$('[data-arena]'),playerEl:$('[data-player]'),enemyEl:$('[data-enemy]'),playerHealth:$('[data-player-health]'),enemyHealth:$('[data-enemy-health]'),playerMeter:$('[data-player-meter]'),enemyMeter:$('[data-enemy-meter]'),time:$('[data-time]'),playerSpecial:$('[data-player-special]'),enemySpecial:$('[data-enemy-special]'),playerSpecialMeter:$('[data-player-special-meter]'),enemySpecialMeter:$('[data-enemy-special-meter]'),callout:$('[data-callout]'),impact:$('[data-impact]'),power:$('[data-power-effect]'),action:$('[data-action-name]'),start:$('[data-start]'),restart:$('[data-restart]'),specialButton:$('[data-action="special"]'),principleButton:$('[data-action="principle"]')};
const state={selected:false,running:false,ended:false,last:0,time:60,aiDecision:0,firstSpecial:{player:true,enemy:true},keys:{left:false,right:false,defend:false},player:null,enemy:null};
const fresh=(id,x)=>({id,profile:profiles[id],x,hp:profiles[id].hp,special:0,defending:false,attacking:false,cooldown:0,hitUntil:0,invulnerableUntil:0,mode:'idle'});
const editable=el=>el&&(el.matches('input,textarea,select,[contenteditable="true"]')||el.closest('input,textarea,select,[contenteditable="true"]'));
const distance=()=>Math.abs(state.enemy.x-state.player.x),upper=s=>s.toLocaleUpperCase('pt-BR');
function portrait(el,id){el.className=`portrait portrait--${id}`;el.style.backgroundImage=`url('assets/arco2/post6-prototype/${id==='parmenides'?'parmenides-neutro-v2':id+'-neutro'}.png')`;}
function configureMatch(){
  const p=state.player.profile,e=state.enemy.profile;ui.playerEl.dataset.fighter=state.player.id;ui.enemyEl.dataset.fighter=state.enemy.id;ui.playerEl.setAttribute('aria-label',p.name);ui.enemyEl.setAttribute('aria-label',e.name);
  $('[data-player-name]').textContent=upper(p.name);$('[data-enemy-name]').textContent=upper(e.name);$('[data-player-special-name]').textContent=`${upper(p.name)} · ESPECIAL`;$('[data-enemy-special-name]').textContent=`${upper(e.name)} · ESPECIAL`;
  $('[data-basic-label]').textContent=p.basic;$('[data-principle-label]').textContent=p.principle;$('[data-special-label]').textContent=p.special;
  $('[data-hold="left"]').setAttribute('aria-label',`Mover ${p.name} para a esquerda`);$('[data-hold="right"]').setAttribute('aria-label',`Mover ${p.name} para a direita`);
  portrait($('.fighter-hud--player .portrait'),state.player.id);portrait($('.fighter-hud--enemy .portrait'),state.enemy.id);ui.frame.className=`fight-frame theme-${state.player.id}`;
}
function selectFighter(id){const rivals=Object.keys(profiles).filter(key=>key!==id),enemyId=rivals[Math.floor(Math.random()*rivals.length)];state.player=fresh(id,27);state.enemy=fresh(enemyId,73);state.selected=true;state.running=false;state.ended=false;state.time=60;state.aiDecision=0;state.firstSpecial={player:true,enemy:true};configureMatch();ui.selection.hidden=true;ui.callout.className='round-callout';ui.callout.innerHTML=`<strong>${upper(profiles[id].name)}</strong><span>${profiles[id].principle} · ${profiles[id].special}<br>Adversário: ${profiles[enemyId].name}</span>`;ui.start.hidden=false;ui.start.textContent='LUTAR';render();}
function showSelection(){state.running=false;state.selected=false;state.ended=false;ui.selection.hidden=false;ui.start.hidden=true;ui.action.className='action-name';ui.power.className='power-effect';}
function setClass(el,f,isPlayer){let mode=f.mode;if(!f.attacking&&!f.defending)mode=(isPlayer&&(state.keys.left||state.keys.right))||(!isPlayer&&state.running&&distance()>15)?'run':'idle';const now=performance.now();el.className=`fighter ${isPlayer?'fighter--player':'fighter--enemy'} state-${mode}${isPlayer?'':' facing-left'}${f.hitUntil>now?' is-hit':''}${f.invulnerableUntil>now?' is-invulnerable':''}${f.hp<=0?' is-ko':''}`;}
function render(){if(!state.selected)return;const p=state.player,e=state.enemy;ui.playerEl.style.setProperty('--x',`${p.x}%`);ui.enemyEl.style.setProperty('--x',`${e.x}%`);ui.playerHealth.style.width=`${p.hp/p.profile.hp*100}%`;ui.enemyHealth.style.width=`${e.hp/e.profile.hp*100}%`;ui.playerMeter.setAttribute('aria-valuemax',p.profile.hp);ui.enemyMeter.setAttribute('aria-valuemax',e.profile.hp);ui.playerMeter.setAttribute('aria-valuenow',Math.round(p.hp));ui.enemyMeter.setAttribute('aria-valuenow',Math.round(e.hp));ui.playerSpecial.style.width=`${p.special}%`;ui.enemySpecial.style.width=`${e.special}%`;ui.playerSpecialMeter.setAttribute('aria-valuenow',Math.round(p.special));ui.enemySpecialMeter.setAttribute('aria-valuenow',Math.round(e.special));ui.specialButton.disabled=p.special<100||!state.running;ui.specialButton.setAttribute('aria-disabled',String(ui.specialButton.disabled));ui.specialButton.classList.toggle('is-ready',p.special>=100&&state.running);ui.time.textContent=Math.ceil(state.time);setClass(ui.playerEl,p,true);setClass(ui.enemyEl,e,false);$('[data-hold="defend"]').setAttribute('aria-pressed',String(p.defending));}
function start(){if(!state.selected||state.running)return;if(state.ended){showSelection();return;}state.running=true;state.last=performance.now();ui.callout.innerHTML='<strong>LUTE!</strong><span>Quatro princípios. Uma disputa.</span>';ui.start.hidden=true;setTimeout(()=>ui.callout.classList.add('hidden'),550);ui.arena.focus({preventScroll:true});requestAnimationFrame(loop);render();}
function showAction(text,d=650){ui.action.textContent=text;ui.action.classList.add('is-visible');clearTimeout(showAction.timer);showAction.timer=setTimeout(()=>ui.action.classList.remove('is-visible'),d);}
function showPower(kind){ui.power.className=`power-effect ${kind}`;void ui.power.offsetWidth;setTimeout(()=>ui.power.className='power-effect',950);}
function charge(f,n){f.special=clamp(f.special+n,0,100);}
function hit(target,attacker,damage,push){if(target.invulnerableUntil>performance.now())return;const actual=target.defending?Math.max(1,Math.round(damage*.35)):damage;target.hp=clamp(target.hp-actual,0,target.profile.hp);target.hitUntil=performance.now()+170;charge(target,target.defending?3:7);charge(attacker,target.defending?5:10);ui.impact.style.left=`${(attacker.x+target.x)/2}%`;ui.impact.classList.remove('show');void ui.impact.offsetWidth;ui.impact.classList.add('show');if(!target.defending)target.x=clamp(target.x+push,8,92);if(target.hp<=0)finish();}
function perform(attacker,target,isPlayer,type){if(!state.running||attacker.cooldown>0||attacker.attacking)return;const principle=type==='principle',range=principle?attacker.profile.principleRange:20,damage=principle?attacker.profile.principleDamage:attacker.profile.basicDamage;attacker.attacking=true;attacker.mode='attack';attacker.cooldown=principle?1.1:.68;showAction(`${upper(attacker.profile.name)} · ${principle?attacker.profile.principle:attacker.profile.basic}`);if(principle)showPower(`principle-${attacker.profile.theme==='fire'?'player':attacker.profile.theme==='stone'?'enemy':attacker.profile.theme}`);setTimeout(()=>{if(state.running&&distance()<=range){let push=isPlayer?3:-3;if(principle)push=isPlayer?(attacker.id==='anaximenes'?10:6):(attacker.id==='anaximenes'?-10:-6);hit(target,attacker,damage,push);}setTimeout(()=>{attacker.attacking=false;attacker.mode='idle';render();},principle?350:280);},principle?160:100);render();}
function special(attacker,target,isPlayer){if(!state.running||attacker.special<100||attacker.attacking)return;attacker.special=0;attacker.attacking=true;attacker.mode=attacker.id==='parmenides'?'defend':'attack';attacker.cooldown=1.65;showAction(`${upper(attacker.profile.name)} · ${attacker.profile.special}`,1050);showPower(`special-${attacker.profile.theme==='fire'?'player':attacker.profile.theme==='stone'?'enemy':attacker.profile.theme}`);const owner=isPlayer?'player':'enemy';if(state.firstSpecial[owner]){state.firstSpecial[owner]=false;ui.callout.className='round-callout';ui.callout.innerHTML=`<strong>${attacker.profile.special}</strong><span>${attacker.profile.phrase}</span>`;setTimeout(()=>ui.callout.classList.add('hidden'),760);}if(attacker.id==='parmenides')attacker.invulnerableUntil=performance.now()+1900;setTimeout(()=>{if(state.running&&distance()<=attacker.profile.specialRange){const push=isPlayer?(attacker.id==='anaximenes'?14:9):(attacker.id==='anaximenes'?-14:-9);hit(target,attacker,attacker.profile.specialDamage,push);}},280);setTimeout(()=>{attacker.attacking=false;attacker.mode='idle';render();},900);render();}
function finish(){if(state.ended)return;state.running=false;state.ended=true;const winnerFighter=state.player.hp===state.enemy.hp?null:(state.player.hp>state.enemy.hp?state.player:state.enemy);const winner=winnerFighter?`${upper(winnerFighter.profile.name)} PREVALECEU`:'RESULTADO NÃO CONCLUSIVO';ui.callout.className='round-callout result';ui.callout.innerHTML=`<strong>CONFRONTO ENCERRADO</strong><span>${winner} nesta disputa.<br>Outras explicações permanecem disponíveis.</span>`;ui.start.hidden=false;ui.start.textContent='OUTRO CONFRONTO';try{localStorage.setItem('sofia-arche-fight-completed','true');localStorage.setItem('sofia-arche-last-fighter',state.player.id);localStorage.setItem('sofia-arche-last-result',winnerFighter?.id===state.player.id?'victory':winnerFighter?'defeat':'draw');}catch{}window.parent?.postMessage({type:'sofia:arche-fight-completed',fighter:state.player.id,result:winnerFighter?.id===state.player.id?'victory':winnerFighter?'defeat':'draw'},location.origin);render();}
function decideAI(){if(!state.running)return;const e=state.enemy,d=distance(),r=Math.random();e.defending=false;if(e.special>=100&&d<=e.profile.specialRange&&r<.42)special(e,state.player,false);else if(d>e.profile.principleRange)e.x-=e.profile.speed*.085;else if(d>20&&r<.58)perform(e,state.player,false,'principle');else if(d>19)e.x-=e.profile.speed*.055;else if(r<.15){e.defending=true;e.mode='defend';showAction(`${upper(e.profile.name)} · DEFESA`);setTimeout(()=>{e.defending=false;e.mode='idle';render();},430+Math.random()*220);}else if(r<.84)perform(e,state.player,false,'basic');else e.x=clamp(e.x+2.5,8,92);state.aiDecision=.12+Math.random()*.17;}
function update(dt){const p=state.player,e=state.enemy;if(state.keys.left&&!p.attacking)p.x-=p.profile.speed*dt;if(state.keys.right&&!p.attacking)p.x+=p.profile.speed*dt;p.x=clamp(p.x,8,92);e.x=clamp(e.x,8,92);if(p.x>e.x-8)p.x=e.x-8;p.x=Math.max(8,p.x);p.defending=state.keys.defend&&!p.attacking;p.mode=p.defending?'defend':p.mode;p.cooldown=Math.max(0,p.cooldown-dt);e.cooldown=Math.max(0,e.cooldown-dt);charge(p,dt*2.3);charge(e,dt*2.05);state.aiDecision-=dt;if(state.aiDecision<=0)decideAI();state.time=Math.max(0,state.time-dt);if(state.time<=0)finish();}
function loop(now){if(!state.running)return;const dt=Math.min(.04,(now-state.last)/1000);state.last=now;update(dt);render();requestAnimationFrame(loop);}
function hold(name,on,button){state.keys[name]=on;if(button)button.classList.toggle('is-held',on);if(name==='defend'&&state.selected){state.player.defending=on&&state.running&&!state.player.attacking;state.player.mode=state.player.defending?'defend':'idle';if(on&&state.running)showAction(`${upper(state.player.profile.name)} · DEFESA`);}render();}
$$('[data-select-fighter]').forEach(b=>b.addEventListener('click',()=>selectFighter(b.dataset.selectFighter)));$$('[data-hold]').forEach(b=>{const n=b.dataset.hold;b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);hold(n,true,b);});['pointerup','pointercancel','lostpointercapture'].forEach(ev=>b.addEventListener(ev,()=>hold(n,false,b)));});
$('[data-action="attack"]').addEventListener('pointerdown',e=>{e.preventDefault();if(state.selected)perform(state.player,state.enemy,true,'basic');});ui.principleButton.addEventListener('pointerdown',e=>{e.preventDefault();if(state.selected)perform(state.player,state.enemy,true,'principle');});ui.specialButton.addEventListener('pointerdown',e=>{e.preventDefault();if(state.selected)special(state.player,state.enemy,true);});ui.start.addEventListener('click',start);ui.restart.addEventListener('click',showSelection);
document.addEventListener('keydown',e=>{if(editable(e.target)||!state.selected)return;const k=e.key.toLowerCase();if(['a','d','j','k','l','arrowleft','arrowright',' '].includes(k))e.preventDefault();if(k==='a'||k==='arrowleft')hold('left',true);if(k==='d'||k==='arrowright')hold('right',true);if(k==='k')hold('defend',true);if(k==='j'&&!e.repeat)perform(state.player,state.enemy,true,'basic');if(k==='l'&&!e.repeat)perform(state.player,state.enemy,true,'principle');if(k===' '&&!e.repeat&&state.running)special(state.player,state.enemy,true);if(k==='enter'&&!state.running&&!e.repeat)start();});document.addEventListener('keyup',e=>{const k=e.key.toLowerCase();if(k==='a'||k==='arrowleft')hold('left',false);if(k==='d'||k==='arrowright')hold('right',false);if(k==='k')hold('defend',false);});window.addEventListener('blur',()=>{hold('left',false);hold('right',false);hold('defend',false);});showSelection();
})();
